"Micro Curso" de Docker..
Play-Dev-Community/blog pull request #8
Opened 2024-10-17 23:29 UTC by op3ny

Um artigo falando o básico sobre docker, interessante para devs interessados em docker em geral.

2024-10-17 23:30 UTC, op3ny commented
* No 2° commit eu alterei a parte do "cabeçalho", porquê dei o commit sem essa parte kskdjasjkdakjhs

2024-10-19 09:05 UTC, gabrielmoodlight requested changes

2024-10-20 03:33 UTC, op3ny commented on docker-aula.md
> +title: Como usar o docker? (Aula de Bash - Parte 3)
Seria uma aula de bash 3, com o tema de docker

2024-10-20 03:37 UTC, gabrielmoodlight approved these changes

2024-10-20 03:37 UTC, merged